export const tags = [
  { value: "Tech", label: "Tech" },
  { value: "Lifestyle", label: "Lifestyle" },
  { value: "Business", label: "Business" },
  { value: "Health", label: "Health" },
  { value: "Sports", label: "Sports" },
  { value: "Education", label: "Education" },
  { value: "Politics", label: "Politics" },
  { value: "national", label: "National" },
  { value: "economy", label: "Economy" },
  { value: "invention", label: "Invention" },
  { value: "medical", label: "Medical" },
  { value: "hospital", label: "Hospital" },
  { value: "crime", label: "Crime" },
  { value: "law", label: "Law" },
  { value: "football", label: "Footbal" },
  { value: "cricket", label: "Cricket" },
  { value: "river", label: "River" },
  { value: "tree", label: "Tree" },
  { value: "village", label: "Village" },
  { value: "school	", label: "School" },
  { value: "news", label: "News" },
  { value: "International", label: "International" },
  { value: "entertainment", label: "Entertainment" },
  { value: "accident", label: "Accident" },
];
